### ISSUE TITLE
v12 compability?

### ISSUE THREAD

**Issue by dpriskorn** [cmfpmatik/theme-dolibarr-md-ux#2]
What would be needed to make it compatible? I am willing to help with pull requests if it is free software.

**Comment by cmfpmatik** [comment]
yes it is.

**Comment by dpriskorn** [comment]
I just saw that there is now responsive support in theme eldy in dolibarr core. I will not work on this because the css-code looks like a nightmare and I just created this issue: https://github.com/Dolibarr/dolibarr/issues/14414

**Comment by cmfpmatik** [comment]
It is good now :)
